spring:
  config:
    import: optional:file:.env
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/second_project
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 5MB

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10

  cache:
    disabled: true

file:
  directory: ${DEFAULT.FILE_PATH}


app:
  jwt:
    secret: ${JWT_SECRET}
    # JWT 만들 때 사용하는 열쇠 > 후에 복호화에 사용
    header-schema-name: authorization #키 이름
    token-type: Bearer #토큰의 종류
    access-token-expiry: 1_800_000 #1시간
    refresh-token-expiry: 1_296_000_000 #15일

---
spring:
  config:
    activate:
      on-profile: tdd
  datasource:
    url: jdbc:mariadb://localhost:3306/second_project_tdd
  sql:
    init:
      mode: always
